import { Task, Project } from './types';

export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj-fuellinkpro',
    name: 'FuelLinkPro',
    description: 'Weekend Build Board — Stabilise → Automate → Scale',
    color: '#5b5bd6',
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'proj-personal',
    name: 'Personal',
    description: 'Personal tasks and goals',
    color: '#38a169',
    createdAt: '2026-08-01T00:00:00.000Z',
  },
];

export const SEED_TASKS: Task[] = [
  // TODAY
  {
    id: 'task-001',
    projectId: 'proj-fuellinkpro',
    title: 'Index FuelLinkPro on Google',
    description: 'Submit sitemap and verify indexing via Google Search Console.',
    priority: 'HIGH',
    status: 'PENDING',
    timeTarget: 'TODAY',
    dueDate: '2026-08-28',
    estimatedEffort: 'HALF_DAY',
    notes: 'Check robots.txt first. Make sure no noindex meta tags are present.',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-002',
    projectId: 'proj-fuellinkpro',
    title: 'Set up Google Search Console',
    description: 'Verify domain ownership and connect to Search Console.',
    priority: 'HIGH',
    status: 'PENDING',
    timeTarget: 'TODAY',
    dueDate: '2026-08-28',
    estimatedEffort: 'QUICK',
    notes: '',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-003',
    projectId: 'proj-fuellinkpro',
    title: 'Create and fix sitemap.xml',
    description: 'Generate a complete sitemap for all public routes.',
    priority: 'HIGH',
    status: 'PENDING',
    timeTarget: 'TODAY',
    dueDate: '2026-08-28',
    estimatedEffort: 'QUICK',
    notes: 'Include all public pages. Exclude admin/auth routes.',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  // THIS WEEK
  {
    id: 'task-004',
    projectId: 'proj-fuellinkpro',
    title: 'Create and fix robots.txt',
    description: 'Ensure robots.txt allows indexing of public pages and blocks private routes.',
    priority: 'HIGH',
    status: 'PENDING',
    timeTarget: 'THIS_WEEK',
    dueDate: '2026-08-30',
    estimatedEffort: 'QUICK',
    notes: '',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-005',
    projectId: 'proj-fuellinkpro',
    title: 'Disable Premium features',
    description: 'Temporarily disable all premium-tier features behind a feature flag.',
    priority: 'MEDIUM',
    status: 'PENDING',
    timeTarget: 'THIS_WEEK',
    dueDate: '2026-08-30',
    estimatedEffort: 'HALF_DAY',
    notes: 'Use environment variable PREMIUM_ENABLED=false.',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-006',
    projectId: 'proj-fuellinkpro',
    title: 'Add Premium feature flag',
    description: 'Implement a clean feature flag system for Premium gating.',
    priority: 'MEDIUM',
    status: 'PENDING',
    timeTarget: 'THIS_WEEK',
    dueDate: '2026-09-01',
    estimatedEffort: 'FULL_DAY',
    notes: '',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  // THIS MONTH — Security
  {
    id: 'task-007',
    projectId: 'proj-fuellinkpro',
    title: 'Enhance failed-login security',
    description: 'Implement rate limiting and account lockout after failed login attempts.',
    priority: 'HIGH',
    status: 'PENDING',
    timeTarget: 'THIS_MONTH',
    dueDate: '2026-09-07',
    estimatedEffort: 'FULL_DAY',
    notes: 'Weekend 2 — Security sprint.',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-008',
    projectId: 'proj-fuellinkpro',
    title: 'Enhance password-reset security',
    description: 'Add expiring tokens and one-time-use reset links.',
    priority: 'HIGH',
    status: 'PENDING',
    timeTarget: 'THIS_MONTH',
    dueDate: '2026-09-07',
    estimatedEffort: 'FULL_DAY',
    notes: '',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-009',
    projectId: 'proj-fuellinkpro',
    title: 'Implement suspicious-account flagging',
    description: 'Flag accounts with unusual login patterns or multiple failed attempts.',
    priority: 'MEDIUM',
    status: 'PENDING',
    timeTarget: 'THIS_MONTH',
    dueDate: '2026-09-07',
    estimatedEffort: 'WEEKEND',
    notes: '',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  // BACKLOG
  {
    id: 'task-010',
    projectId: 'proj-fuellinkpro',
    title: 'Fix system_logs',
    description: 'Audit and repair the system_logs table schema and event recording.',
    priority: 'MEDIUM',
    status: 'PENDING',
    timeTarget: 'BACKLOG',
    dueDate: null,
    estimatedEffort: 'WEEKEND',
    notes: 'Weekend 3 — System Control sprint.',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-011',
    projectId: 'proj-fuellinkpro',
    title: 'Record authentication events',
    description: 'Log all auth events (login, logout, reset, failed) to system_logs.',
    priority: 'MEDIUM',
    status: 'PENDING',
    timeTarget: 'BACKLOG',
    dueDate: null,
    estimatedEffort: 'FULL_DAY',
    notes: '',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  {
    id: 'task-012',
    projectId: 'proj-fuellinkpro',
    title: 'Move important settings into system_settings',
    description: 'Migrate hardcoded config values into the system_settings table.',
    priority: 'LOW',
    status: 'PENDING',
    timeTarget: 'BACKLOG',
    dueDate: null,
    estimatedEffort: 'FULL_DAY',
    notes: '',
    attachments: [],
    createdAt: '2026-08-28T06:00:00.000Z',
    completedAt: null,
    emailNotificationStatus: 'NOT_SENT',
  },
  // COMPLETED
  {
    id: 'task-013',
    projectId: 'proj-fuellinkpro',
    title: 'Enhance FuelLinkPro customer dashboard',
    description: 'Improved data visualisation and performance metrics on the customer dashboard.',
    priority: 'HIGH',
    status: 'COMPLETED',
    timeTarget: 'THIS_WEEK',
    dueDate: '2026-08-24',
    estimatedEffort: 'WEEKEND',
    notes: 'Pushed to production on 24 Aug.',
    attachments: [],
    createdAt: '2026-08-20T09:00:00.000Z',
    completedAt: '2026-08-24T17:30:00.000Z',
    emailNotificationStatus: 'SENT',
  },
  {
    id: 'task-014',
    projectId: 'proj-fuellinkpro',
    title: 'Fix payment callback',
    description: 'Resolved race condition in the payment webhook handler.',
    priority: 'HIGH',
    status: 'COMPLETED',
    timeTarget: 'TODAY',
    dueDate: '2026-08-20',
    estimatedEffort: 'HALF_DAY',
    notes: '',
    attachments: [],
    createdAt: '2026-08-19T08:00:00.000Z',
    completedAt: '2026-08-20T14:15:00.000Z',
    emailNotificationStatus: 'SENT',
  },
  {
    id: 'task-015',
    projectId: 'proj-personal',
    title: 'Deploy dashboard update',
    description: 'Deployed the latest Tethra dashboard changes to production.',
    priority: 'MEDIUM',
    status: 'COMPLETED',
    timeTarget: 'TODAY',
    dueDate: '2026-08-20',
    estimatedEffort: 'QUICK',
    notes: '',
    attachments: [],
    createdAt: '2026-08-20T10:00:00.000Z',
    completedAt: '2026-08-20T11:45:00.000Z',
    emailNotificationStatus: 'NOT_SENT',
  },
];
